title: What is a tensor? Tensors from physics explained in unnecessary rigour using concepts from functional programming

<!-- MathJax -->
<script type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

